language: php

sudo: false

php:
    - 7.0
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
  - TRAVIS_NODE_VERSION="4"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.gi thttps://github.com/creationix/nvm.gitAd~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev --no-interaction

script:
    - vendor/bin/codecept run
